#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=jdbc:mysql://localhost:3306/manischema
#spring.datasource.username=root
#spring.datasource.password=admin
#logging.level.root=WARN
server.port =8081

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# Custom application name (appears in metrics)
spring.application.name=Spring-Restdemo

# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true
